local   all             all                                     scram-sha-256
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256
host    postgres        pgbouncer_auth  10.250.0.10/32          scram-sha-256
host    all             postgres        10.250.0.10/32          reject
host    all             backup          10.250.0.10/32          reject
host    sameuser        all             10.250.0.10/32          scram-sha-256
host    all             all             10.250.0.10/32          reject
host    all             postgres        10.250.0.0/24           scram-sha-256
host    all             backup          10.250.0.0/24           scram-sha-256
host    all             all             all                     reject
