host    all         pgbouncer_auth                      0.0.0.0/0       reject
host    pgbouncer   pgbouncer_admin,pgbouncer_stats     127.0.0.1/32    scram-sha-256
host    pgbouncer   pgbouncer_admin,pgbouncer_stats     10.250.0.0/24   scram-sha-256
host    all         pgbouncer_admin,pgbouncer_stats     0.0.0.0/0       reject
host    all         all                                 0.0.0.0/0       scram-sha-256
